<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-24 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255, verbose_name='المقال')),
                ('article_details', models.TextField(verbose_name='تفاصيل المقال')),
                ('article_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط المقال')),
                ('publish_date', models.DateField(verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('status', models.CharField(choices=[('in_progress', '⏳ جاري العمل'), ('upload', 'تم الرفع'), ('publish', 'تم النشر'), ('done', '✅ مكتملة')], default='in_progress', max_length=20, verbose_name='حالة المهمة')),
                ('publish_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.site', verbose_name='موقع النشر')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
        ),
    ]
=======
# Generated by Django 5.2.3 on 2025-06-24 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255, verbose_name='المقال')),
                ('article_details', models.TextField(verbose_name='تفاصيل المقال')),
                ('article_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط المقال')),
                ('publish_date', models.DateField(verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('status', models.CharField(choices=[('in_progress', '⏳ جاري العمل'), ('upload', 'تم الرفع'), ('publish', 'تم النشر'), ('done', '✅ مكتملة')], default='in_progress', max_length=20, verbose_name='حالة المهمة')),
                ('publish_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.site', verbose_name='موقع النشر')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
        ),
    ]
>>>>>>> d7023bb44d462afe13064eb16464741bb8208045
