# Generated by Django 5.2.3 on 2025-06-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_article_type_w_r_a_b_number_of_article'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Article_type_W_R_A_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.article_type_w_r_a_b', verbose_name='( تحذير / تقييم/تعليمي/افضل شركات)نوع المقال'),
        ),
        migrations.AddField(
            model_name='task',
            name='article_type_U_N',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.article_type_u_n', verbose_name='(تحديث ام جديد)نوع المقال'),
        ),
    ]
